import walls,wrap

walls.wall("     XXXXX     XXXXX              ")
walls.wall("     X   X     X   X              ")
walls.wall("    XX   XXXXXXXXXXX             ")
walls.wall("XXXXX       X       XXXXXXXXXXXXXX")
walls.wall("X           X       X            X")
walls.wall("X           X       X            X")
walls.wall("XXXXX       X      X             X")
walls.wall("X           XXXXXXXXXX     XXXXXXX")
walls.wall("X           X                    X")
walls.wall("XXXXXXXXX   X                    X")
walls.wall("X           X                    X")
walls.wall("X           X            X   XXXXX")
walls.wall("X                        X       X")
walls.wall("X                        X       X")
walls.wall("XXXXXXXXXXXXX            XXXXXXXXX")
walls.wall("X           X            X       X")
walls.wall("X                                X")
walls.wall("X                                X")
walls.wall("XXXXXXXX  XXX     XXXXXXXXXXXXXXXX")
walls.wall("XXXXXXXX  XXX         X        XXX")
walls.wall("XXXXXXXX  XXX         X        XXX")
walls.wall("XXXX        X         X        XXX")
walls.wall("XXXX        X       XXXXX      XXX")
walls.wall("XXXX        X                  XXX")
walls.wall("XXXXXXX  XXXX                  XXX")
walls.wall("XXXXXXX  XXXX       XXXXX      XXX")
walls.wall("XXXXXXX  XXXX         X        XXX")
walls.wall("XX         XX         X        XXX")
walls.wall("XX         XX         X        XXX")
walls.wall("XXXXXXXXXXXXX     XXXXXXXXXXXXXXXX")
walls.wall("X                                X")
walls.wall("X                                X")
walls.wall(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ")
